// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResturantAPI.Models;

namespace ResturantAPI.Migrations
{
    [DbContext(typeof(ResturantDbContext))]
    [Migration("20200217161305_CategorysTable")]
    partial class CategorysTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ResturantAPI.Models.BE.Categorys", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("DescriptionSeo");

                    b.Property<bool>("IsMenu");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("KeywordsSeo");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<string>("TitleSeo");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Categorys");
                });
#pragma warning restore 612, 618
        }
    }
}
